name: Sync Upstream

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时执行一次
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork repository
        uses: actions/checkout@v4
        with:
          ref: main
          persist-credentials: false

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/colaxr/sublinkx.git
          git fetch upstream

      - name: Merge upstream main into fork main
        run: |
          git checkout main
          git merge upstream/main --no-edit || echo "No changes to merge"

      - name: Push changes to fork using PAT_TOKEN
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}.git
          git push origin main || echo "Nothing to push"
